### ISSUE TITLE
PropType error

### ISSUE THREAD

**Issue by norraell** [brunnolou/react-morph#15]
In each demo of yours (https://codesandbox.io/s/j2rjln010w and https://codesandbox.io/s/96x66mr6w) and in my code I see a warning in my console.
`Warning: Failed prop type: checker is not a function
    in Morph`

Maybe there is something wrong with the specified propTypes?

Best regards :)

**Comment by weslleyaraujo** [comment]
hey! I got exactly the same, trying to debug now to see if I find what it is 🤞

**Comment by weslleyaraujo** [comment]
also, it looks like popmotion released a breaking change or something:

```
Module not found: Can't resolve 'popmotion/animations/keyframes' in ~/react-morph/lib'
````
That is solved if I manually install version `8.1.0`:

```bash
yarn add popmotion@8.1.10
```

**Comment by weslleyaraujo** [comment]
looks like the problem is at proptypes definition at [`src/index.js#L97`](https://github.com/brunnolou/react-morph/blob/master/src/index.js#L97), both `restDelta` and `restSpeed` are defining numbers as proptypes (probably confused as `defaultProps` values)

Changing that to `propTypes.number` and moving those values to `defaultProps` will fix the issue.

@brunnolou I can send a PR with that if it makes sense 🕺

**Comment by StevenSchlotterbeck** [comment]
@weslleyaraujo I'm also encountering the error with popmotion's breaking change, updating the package.json to reference 8.1.0 solved for me as well:

```
"popmotion": "~8.1.10",
```

Was getting this error:

```
These dependencies were not found:

* popmotion/animations/keyframes in ./node_modules/react-morph/lib/index.js
* popmotion/animations/spring in ./node_modules/react-morph/lib/index.js
* popmotion/animations/tween in ./node_modules/react-morph/lib/index.js
* popmotion/easing in ./node_modules/react-morph/lib/index.js
* popmotion/reactions/value in ./node_modules/react-morph/lib/index.js
* popmotion/transformers in ./node_modules/react-morph/lib/index.js
```
